services:
  - type: web
    name: chatbotweb
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GEMINI_API_KEY
        sync: false

databases:
  - name: chatbotdb
    databaseName: chatbotdb
    user: chatbot
    plan: free
